{% set name = "pybv" %}
{% set version = "0.7.6" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 518dac9bf151601c45787bf0ddcc5e37afd61033058eb734067825f8ae46d51b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - numpy >=1.18.1

test:
  requires:
    - python {{ python_min }}
  imports:
    - pybv
    - pybv.io

about:
  home: https://pybv.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A lightweight I/O utility for the BrainVision data format, written in Python
  dev_url: https://github.com/bids-standard/pybv

extra:
  recipe-maintainers:
    - larsoner
    - hoechenberger
    - sappelhoff
