{% set name = "pybv" %}
{% set version = "0.8.1" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 31cd29612d8d35eda752b992e79da1db9d81bdf9e703743cd863ab2eeb446f22

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - numpy >=1.18.1

test:
  requires:
    - python {{ python_min }}
  imports:
    - pybv
    - pybv.io

about:
  home: https://pybv.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A lightweight I/O utility for the BrainVision data format, written in Python
  dev_url: https://github.com/bids-standard/pybv

extra:
  recipe-maintainers:
    - larsoner
    - hoechenberger
    - sappelhoff
