{% set name = "pybv" %}
{% set version = "0.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a4fe6c0edffbc70bc8556cbae693c397f4254a522427eaeae9351ec825be77b7

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy >=1.18.1

test:
  imports:
    - pybv
    - pybv.io

about:
  home: https://pybv.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A lightweight I/O utility for the BrainVision data format, written in Python
  dev_url: https://github.com/bids-standard/pybv

extra:
  recipe-maintainers:
    - larsoner
    - hoechenberger
    - sappelhoff
