{% set name = "pybv" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 07301aa19effba394d1bec03699e476e34e60f4b9fd0b04161203a40b10d9b74

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy

test:
  imports:
    - pybv
    - pybv.io

about:
  home: https://pybv.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A lightweight I/O utility for the BrainVision data format, written in Python
  dev_url: https://github.com/bids-standard/pybv

extra:
  recipe-maintainers:
    - hoechenberger
    - sappelhoff
